# Generated by Django 4.0.2 on 2022-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jiance_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('PLC_state', models.BooleanField(verbose_name='PLC运行状态')),
                ('touch_screen_state', models.BooleanField(verbose_name='触摸屏运行状态')),
                ('flat_panel_detector_state', models.BooleanField(verbose_name='平板探测器运行状态')),
                ('shexianyuan_state', models.BooleanField(verbose_name='射线源运行状态')),
                ('robot_state', models.BooleanField(verbose_name='机器人运行状态')),
                ('industrial_state', models.BooleanField(verbose_name='工控机运行状态')),
                ('camera1_state', models.BooleanField(verbose_name='监控摄像头1运行状态')),
                ('camera2_state', models.BooleanField(verbose_name='监控摄像头2运行状态')),
                ('current_feedback', models.FloatField(max_length=8, verbose_name='电流反馈')),
                ('voltage_feedback', models.FloatField(max_length=8, verbose_name='电压反馈')),
            ],
        ),
        migrations.CreateModel(
            name='manual_input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('zaoxing_model_information', models.CharField(max_length=16, verbose_name='造型模型信息')),
                ('vibrational_frequency', models.FloatField(max_length=8, verbose_name='振动频率')),
                ('alloy_designation', models.CharField(max_length=16, verbose_name='合金牌号')),
                ('total_melt_amount', models.FloatField(max_length=8, verbose_name='总熔化量')),
                ('small_allowance', models.FloatField(max_length=8, verbose_name='中间合金小块锭余量')),
                ('zhuzao_model_information', models.CharField(max_length=16, verbose_name='铸造模型信息')),
            ],
        ),
        migrations.CreateModel(
            name='ronglian_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('zhuluti_state', models.BooleanField(verbose_name='主炉体运行状态')),
                ('gas_flow', models.FloatField(max_length=8, verbose_name='天然气流量')),
                ('gas_pressure', models.FloatField(max_length=8, verbose_name='天然气压力')),
                ('fan_pressure', models.FloatField(max_length=8, verbose_name='风机压力')),
                ('furnace_temperature', models.FloatField(max_length=8, verbose_name='炉膛温度')),
                ('liquid_temperature', models.FloatField(max_length=8, verbose_name='溶液温度')),
                ('melt_composition', models.CharField(max_length=16, verbose_name='熔体成分')),
                ('hydrogen_content', models.FloatField(max_length=8, verbose_name='氢含量')),
                ('electromagnetic_stirring_current', models.FloatField(max_length=8, verbose_name='电磁搅拌电流')),
                ('argon_flow', models.FloatField(max_length=8, verbose_name='氩气流量')),
                ('zhuanglu_system_state', models.BooleanField(verbose_name='装炉系统运行状态')),
                ('pure_aluminum_amount', models.FloatField(max_length=8, verbose_name='纯铝加入量')),
                ('alloying_quantity', models.FloatField(max_length=8, verbose_name='中间合金长条锭加入量')),
                ('pure_aluminium_allowance', models.FloatField(max_length=8, verbose_name='纯铝余量')),
                ('alloy_allowance', models.FloatField(max_length=8, verbose_name='中间合金长条锭余量')),
                ('jiliao_system_state', models.BooleanField(verbose_name='给料系统运行状态')),
                ('theory_replenishment_weight', models.FloatField(max_length=8, verbose_name='中间合金理论补给重量')),
                ('actual_replenishment_weight', models.FloatField(max_length=8, verbose_name='中间合金实际补给重量')),
                ('refining_temperature', models.FloatField(max_length=8, verbose_name='精炼温度')),
                ('refining_agent_amount', models.FloatField(max_length=8, verbose_name='精炼剂用量')),
                ('duoxing_gas_flow', models.FloatField(max_length=8, verbose_name='惰性气体流量')),
                ('refining_time', models.FloatField(max_length=8, verbose_name='精炼时间')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('user', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('age', models.CharField(max_length=16, verbose_name='年龄')),
                ('sexy', models.CharField(max_length=8, verbose_name='性别')),
                ('level', models.IntegerField(max_length=8, verbose_name='级别')),
            ],
        ),
        migrations.CreateModel(
            name='zaoxing_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('hunshaji_state', models.BooleanField(verbose_name='混砂机运行状态')),
                ('environment_temperature', models.FloatField(max_length=8, verbose_name='环境温度')),
                ('xingsha_temperature', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='型砂温度')),
                ('gansha_flow_rate', models.FloatField(max_length=8, verbose_name='干砂流量')),
                ('shuzhi_flow_rate', models.FloatField(max_length=8, verbose_name='树脂流量')),
                ('guhuaji1_flow_rate', models.FloatField(max_length=8, verbose_name='固化剂1流量')),
                ('guhuaji2_flow_rate', models.FloatField(max_length=8, verbose_name='固化剂2流量')),
                ('zhenshitai_state', models.BooleanField(verbose_name='振实台运行状态')),
                ('amplitude', models.FloatField(max_length=8, verbose_name='振幅')),
                ('reverse_proportional_valve_signal', models.FloatField(max_length=8, verbose_name='翻转比例阀信号')),
                ('hexiangji_state', models.BooleanField(verbose_name='起模流涂合箱机运行状态')),
                ('oil_temperature', models.FloatField(max_length=8, verbose_name='液压站油温')),
                ('curing_time', models.FloatField(max_length=8, verbose_name='固化时间')),
                ('dry_temperature', models.FloatField(max_length=8, verbose_name='表干温度')),
                ('drying_time', models.FloatField(max_length=8, verbose_name='表干时间')),
            ],
        ),
        migrations.CreateModel(
            name='zhuzao_parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='时间')),
                ('zhuzaoji_state', models.BooleanField(verbose_name='铸造机运行状态')),
                ('jiaozhu_temperature', models.FloatField(max_length=8, verbose_name='浇注熔体温度')),
                ('tank_pressure_on', models.FloatField(max_length=8, verbose_name='上罐压力')),
                ('tank_pressure_off', models.FloatField(max_length=8, verbose_name='下罐压力')),
                ('chongxing_pressure', models.FloatField(max_length=8, verbose_name='充型压力')),
                ('chongxing_time', models.FloatField(max_length=8, verbose_name='充型时间')),
                ('baoya_pressure', models.FloatField(max_length=8, verbose_name='保压压力')),
                ('baoya_time', models.FloatField(max_length=8, verbose_name='凝固保压时间')),
                ('magnetic_field_current', models.FloatField(max_length=8, verbose_name='磁场电流')),
                ('dianzhen_temperature', models.FloatField(max_length=8, verbose_name='点阵温度')),
                ('gongzuocanglongmen_state', models.BooleanField(verbose_name='工作舱龙门运行状态')),
                ('duogongnenglongmen_state', models.BooleanField(verbose_name='多功能龙门运行状态')),
                ('manipulator_state', models.BooleanField(verbose_name='升液管机械手运行状态')),
            ],
        ),
    ]
